name: aShop
version: '${version}'
author: 아포칼립스
main: org.aplugin.ashop.Shop
api-version: '1.21'
depend: [Vault]
commands:
  open:
    description: Open Shop GUI
    permission-message: §f[§aaShop§f]§c권한이 없습니다!
    usage: /open
  아이템등록:
    description: 아이템을 상점에 추가합니다.
    usage: 손에 아이템을 들고 /아이템등록 명령어를 실행하세요
  가격변동:
    description: 가격 변동 관련 커맨드
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.0.0

permissions:
  ashop.*:
    children:
      - ashop.open
      - ashop.item
      - ashop.edit
      - ashop.price